# Generated by Django 4.2.7 on 2023-11-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IP_address", models.CharField(max_length=20)),
                ("time", models.DateTimeField(verbose_name="time visiting")),
            ],
        ),
    ]
