# Generated by Django 4.2.7 on 2023-12-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IP_address", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("time", models.DateTimeField(verbose_name="time visiting")),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32)),
                ("message", models.CharField(max_length=500)),
                ("time", models.DateTimeField(verbose_name="time sent")),
            ],
        ),
    ]
