# Generated by Django 4.2.7 on 2023-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("query", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logging",
            name="location",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
